language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:travis || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - OWNER_NAME: Brightspace
  - REPO_NAME: attachment
  - SAUCE_USERNAME: JennaZ
  - secure: YmOGvog7Fgyh/Xu1N1bf/FmXoKoYrVfvEV1Ipn4xjb7DncELmu6W3e4w60KtasvlePwnbt1mjBNHKb8IkrNnNeYd2NVLrCPu3evYLtvQI0mrfDjN6Tv2pgejMAG8tlM8YEVup5cY7vlJNtCO4pd3m2H+HHPVevPmtUn1aa9Nnc1mnEEI4UN0qy8Uq6B80WMDOzBHuxPeypbixF4QEzqPZtAKjVArRilt1eyspCz6cWx/HiO1C/rwJgEpkIwiwvYLbiX/RTMypQTYT4gAfGVZcb0fByyhmwxQzJ2lzkL8Czj4Vny0oZqkTDtD5aumb1Upk4XvRUOg338AJgp/0CFLHKQ67UOvUPDt658CSrUnXeAFPxC5z8Sm/6dgKG1eZsYA15/OCtnloWKhTijNutKjKAq6E/fxGkoy55KzQnVTUPLhVyhLCUrk3OY2VT++mfaFOs9Shi88uuZ9lVn41MmpdZQFujO4WDz+WewJys+iLBsrQAIdGlPAeF8ZZLVBbErdP7n002EIj9yncvlG3RgLzURDLgqFjyWNO+DAfzRv4po2m4R7wRHu6VDju4parSw7DDNnpfRR62ySkzN4UjmFDJhbClYqRGYkEsCtlNBcJ3O+2jW9f3AOOPvlGo1I+VoYD8QyQImlCujHMV5lb8LSSS22AUkmz3znp2XjHl83M2g=
  - secure: Tf9gTy8IpyVDtLiaE1HDGGMI40SdYJk+7dY5CumZtwsy5GZ2aG8TGVOWjpkZfgjs1GUFkG4xlVjSbWHbHoxYmpALq0qutp5z/vNRWR4gdtk1RzR/ZdgYOpcad2r4ojGdna1Pma7P6F47xNmgHS2GCV42JgN2CuSXTHjZpiZUzL4wTCZ7ud2sn/KUBwW8IiVOSvF+y6UdK9Fj/ZK8wIOc/K3iIyu8cty1bG793XIuLR0X+BNAtHRm9ZnSaKAUArAAZnMpxvKKResTTVcUdroJ9g0ijPTv3Q3xMEpFECBnxRQ71stmV2t8QWni4eT/wSAzgCUf4G4UebrGeWG5DRWQi1QHSvLpIuwSw1RxSkJUJrvZc4cJqxO1oV3ZMDj2GjvbLy0McdMR7gfvNzDa2GhseRbNLvm0VYIJUU54TWF1pu5m2b8qfSrplv+7EPbU4C3RFHTQNG8Oex+woW57NZNorHvn8VMC2EGg/Z6DRAY9W3Vw4niaBnMqsHRIIiC7fTRVUiecUWguEJPDXmglLMruZOEGPs6yCV+OcpAEK79FthEIMPwVp3i0xxXHyhWFhg8inB+MtMSbLWl7/9JgBYvRxr+KCTD5wXLsnVV4RAaie4rlfJMMhdjzRsL7eNKPUMw9u1uWSlowi8dNV9YcA9t5lrH9q5sV084j+//RpWJNDLw=
