language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:travis || travis_terminate 1;
  fi
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspace
  - REPO_NAME: attachment
  - SAUCE_USERNAME: D2L_Federation
  - secure: YmOGvog7Fgyh/Xu1N1bf/FmXoKoYrVfvEV1Ipn4xjb7DncELmu6W3e4w60KtasvlePwnbt1mjBNHKb8IkrNnNeYd2NVLrCPu3evYLtvQI0mrfDjN6Tv2pgejMAG8tlM8YEVup5cY7vlJNtCO4pd3m2H+HHPVevPmtUn1aa9Nnc1mnEEI4UN0qy8Uq6B80WMDOzBHuxPeypbixF4QEzqPZtAKjVArRilt1eyspCz6cWx/HiO1C/rwJgEpkIwiwvYLbiX/RTMypQTYT4gAfGVZcb0fByyhmwxQzJ2lzkL8Czj4Vny0oZqkTDtD5aumb1Upk4XvRUOg338AJgp/0CFLHKQ67UOvUPDt658CSrUnXeAFPxC5z8Sm/6dgKG1eZsYA15/OCtnloWKhTijNutKjKAq6E/fxGkoy55KzQnVTUPLhVyhLCUrk3OY2VT++mfaFOs9Shi88uuZ9lVn41MmpdZQFujO4WDz+WewJys+iLBsrQAIdGlPAeF8ZZLVBbErdP7n002EIj9yncvlG3RgLzURDLgqFjyWNO+DAfzRv4po2m4R7wRHu6VDju4parSw7DDNnpfRR62ySkzN4UjmFDJhbClYqRGYkEsCtlNBcJ3O+2jW9f3AOOPvlGo1I+VoYD8QyQImlCujHMV5lb8LSSS22AUkmz3znp2XjHl83M2g=
  # SAUCE_ACCESS_KEY
  - secure: wX9pafOAktYl1sy56WpAkTZGoR5L3FKaNvx14MP6l+dFImVV/8NAY71ORraMHy8DLA+63nBQKYNiNMBxjyGM6QPdVB+vZdkQMyONTQPTuHtP5Gf8FQrgssKSnuqdbBhBPrCsPxwHgAytRzFn2CA1bLNKqwQoFfEE+Jo+E7FddhZqo6HUENCeDpPT1R2DQQWp7kK7zjAyrNiYutqE1pt08Q6m7fnwLQxh1AlIHxqolgF50PdU1iQSslw8U2kNcfd+2g0qHhyEmJvmrN9q29YsgtR0yDM1ceHulCLAwcLrZtqJh2zF5XESPpgWAA7IpaysfPMq4IpCOvut4/+PUk5gSmDKdIwwUQx6nCuiiEWvR9+WIO1ghZdsLU3ZBFlpCF4qh0BSSrcDrDU/5+PXifgc0xjvQJqMR+Gj+o1oYY8hxAKwGVz17dvc9wK5vgclKA3q7tVgNYMfed7rScId9+A7cVjgbzkCD2fVkkrGO/pxdRE9ogarHDyLg+1UmT4o/Rr9Hp7NHrzksdrmHTv7dvQ5v6WkJa9iy3KnEEr5JlIkbsS5TdiFPQMjf0tSC1p8rZBwq9ooEq8OtgNLD8NgCTJs7bIhXU6jnmCO2iEdJTI8rfGBm3GZcXJcHnyUtEuDbpYunWhJFjGH17RLHlFy8UOtF9jhARNqUzhnCWbu43VbC8A=
